name: mkdocs-build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libopenjp2-7-dev libtiff5-dev tk-dev tcl-dev libcairo2-dev libffi-dev libwebp-dev
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      # - uses: actions/cache@v4
      # with:
      #   key: mkdocs-material-${{ env.cache_id }}
      #   path: .cache
      #   restore-keys: |
      #     mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
