name: mkdocs-build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          set-safe-directory: false
          key: ${{ github.ref }}
          path: .cache
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        with:
          packages: libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
          version: 1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: 3os.org
          CONFIG_FILE: ./mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: ./requirements.txt
